### ISSUE TITLE
Banner Proxy returning cached class data instead of new class data. 

### ISSUE THREAD

**Issue by Jpatel2049** [schedulemaker/banner-proxy#4]
Making a call to the banner proxy works when you first call and every new call to the banner proxy just returns the results of the first call. Appears is version 3 & 4.

**Comment by Jpatel2049** [comment]
![image](https://user-images.githubusercontent.com/46332096/78399745-7af26580-75c3-11ea-801e-bc7f2098fe3a.png)
![image](https://user-images.githubusercontent.com/46332096/78399768-8a71ae80-75c3-11ea-8eae-2d90d1e80ffe.png)

**Comment by Jpatel2049** [comment]
1st picture shows the input. Should return the first 25 CIS courses. 2nd picture shows part of the results and we actually are showing the first 25 MATH courses, which was a query we had made just before.

**Comment by studioph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 4](https://trello.com/c/2iUbKmYv/25-issue-4)
